[package]
name    = "{{demo}}"
version = "0.1.0"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]
edition = "2018"

[dependencies]
rand       = { version = "0.6", features = [ "stdweb" ] }
num-traits = "0.2"
nalgebra   = "0.17"
ncollide2d = "0.18"
kiss3d     = "0.18"

[profile.release]
lto = true

[dependencies.nphysics2d]
path = "{{nphysics2d_dir}}"

[dependencies.nphysics_testbed2d]
path = "{{testbed2d_dir}}"


[[bin]]
name = "{{demo}}"
path = "./{{demo}}.rs"
