[package]
name    = "{{demo}}"
version = "0.1.0"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]

[dependencies]
rand       = { version = "0.5", features = [ "stdweb" ] }
num-traits = "0.2"
nalgebra   = "0.15"
ncollide2d = "0.16"
kiss3d     = "0.15"

[dependencies.nphysics2d]
path = "{{nphysics2d_dir}}"

[dependencies.nphysics_testbed2d]
path = "{{testbed2d_dir}}"


[[bin]]
name = "{{demo}}"
path = "./{{demo}}.rs"
