site_name: nphysics
pages:
  - Home: index.md
  - '<i class="fa fa-book"></i>&nbsp User Guide':
    - 'Getting started': getting_started.md
    - 'Rigid body simulation': rigid_body_simulations_with_contacts.md
    - 'Joint constraints and multibodies': joint_constraints_and_multibodies.md
    - 'Deformable bodies': deformable_bodies.md
    - 'Contact models': contact_models.md
    - 'Interaction handling and sensors': interaction_handling_and_sensors.md
    - 'Performance tuning': performance_tuning.md
    - 'The nphysics testbed': nphysics_testbed.md
    - 'WASM compatibility': wasm_compatibility.md
#     - 'FAQ': faq.md
  - '<i class="fa fa-align-left"></i>&nbsp API Documentation':
    - 'nphysics2d': rustdoc_nphysics2d.md
    - 'nphysics3d': rustdoc_nphysics3d.md
  - '<i class="fa fa-play"></i>&nbsp Demos':
    - '2D demos':
        - 'Stack of balls': demo_balls2.md
        - 'Stack of boxes': demo_boxes2.md
        - 'Convex solids': demo_convex2.md
        - 'Polyline terrain': demo_polyline2.md
        - 'Compound shapes': demo_cross2.md
        - 'Kinematic body': demo_body_status2.md
        - 'Collision groups': demo_collision_groups2.md
        - 'Multibody joints': demo_joints2.md
        - 'Joint constraints': demo_constraints2.md
        - 'Ragdolls': demo_ragdoll2.md
        - 'Sensor': demo_sensor2.md
    - '3D demos':
        - 'Stack of balls': demo_balls3.md
        - 'Stack of boxes': demo_boxes3.md
        - 'Convex solids': demo_convex3.md
        - 'Triangle mesh terrain': demo_trimesh3.md
        - 'Compound shapes': demo_cross3.md
        - 'Kinematic body': demo_body_status3.md
        - 'Collision groups': demo_collision_groups3.md
        - 'Multibody joints': demo_joints3.md
        - 'Joint constraints': demo_constraints3.md
        - 'Ragdolls': demo_ragdoll3.md
        - 'Sensor': demo_sensor3.md

  - '<i class="fa fa-question-circle"></i>&nbsp About':
      - 'Contributing': about.md
      - 'Release notes': changelog.md
theme:
    name: null
    custom_dir: 'custom_flatly'
site_author: 'Sébastion Crozet'
site_favicon: img/favicon.ico
site_url: http://nphysics.org

# the third-party extension mdx_math.py comes with a setup.py script
# Thank you Dmitry Shachnev (https://github.com/mitya57/python-markdown-math)
markdown_extensions:
    - extra
    - mdx_math:
        enable_dollar_delimiter: True #for use of inline $..$
    - fenced_code
    - codehilite:
        use_pygments: False
    - footnotes
    - smarty
    - admonition
    - toc:
        permalink: '§'

# Required to load the MathJax javascript for the mdx_math.py
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']
